version: '3.8'

services:

  guess-game:
    container_name: guess-game-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/config/application.yml