version: '3.8'

services:

  guess-game:
    container_name: guess-game-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - inner_network
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/local.yml,file:/src/main/resources/application.yml

networks:
  inner_network:
    name: inner_network
    ipam:
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1